services:
  - type: web
    name: nftagachi-frontend
    env: node
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: "npm install --prefer-offline --no-audit && NODE_OPTIONS=--max-old-space-size=450 npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: NODE_VERSION
        value: "20.11.0"

  - type: web
    name: nftagachi-lobby
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "10000"
